/* Hous-Q Religious Facility Engine v1.1 */
(()=>{
const $=id=>document.getElementById(id);
const num=v=>Number(String(v??'').replace(/,/g,''))||0;
const fmt=n=>Number(n||0).toLocaleString('en-US');
let busy=false;
function findReligionCard(){return [...document.querySelectorAll('#communityCards .community-card')].find(card=>{const t=card.querySelector('.community-type')?.textContent.trim()||'';return t==='Keagamaan'||t==='Kemudahan Keagamaan'})}
function muslimPopulation(){const units=num($('totalUnits')?.textContent),hh=Math.max(1,num($('household')?.value)||5);if($('muslimMode')?.value==='manual')return Math.max(0,num($('muslimPopulation')?.value));return Math.round(units*.30*hh)}
function breakdown(pop){let bandar=0,kej=0,surau=0;if(pop<=0)return{bandar,kej,surau};const full=Math.floor(pop/10000);bandar+=full;kej+=full*2;surau+=full*4;const r=pop-full*10000;if(r>0&&r<=2500)surau+=1;else if(r<=5000&&r>2500){kej+=1;surau+=2}else if(r>5000){bandar+=1;kej+=2;surau+=4}return{bandar,kej,surau}}
function line(label,value){return `<span style="display:block;text-align:right;white-space:nowrap;line-height:1.45;color:#172234;font-weight:800;">${label}: ${fmt(value)} unit</span>`}
function nameLine(label){return `<span style="display:block;text-align:left;line-height:1.35;">${label}</span>`}
function enhance(){if(busy)return;const card=findReligionCard();if(!card)return;busy=true;const pop=muslimPopulation(),b=breakdown(pop);const result=card.querySelector('.community-result'),rows=card.querySelectorAll('.facility-row strong'),note=card.querySelector('.facility-note'),src=card.querySelector('.community-source'),type=card.querySelector('.community-type');if(!result||rows.length<3){busy=false;return}const names=[],counts=[],areas=[],totals=[];if(b.bandar){names.push('Masjid Bandar');counts.push(line('Masjid Bandar',b.bandar));areas.push('Masjid Bandar: Min. 3.00 ekar');totals.push(`Masjid Bandar: Min. ${(b.bandar*3).toFixed(2)} ekar`)}if(b.kej){names.push('Masjid Kejiranan');counts.push(line('Masjid Kejiranan',b.kej));areas.push('Masjid Kejiranan: Min. 1.50 ekar');totals.push(`Masjid Kejiranan: Min. ${(b.kej*1.5).toFixed(2)} ekar`)}if(b.surau){names.push('Surau Kejiranan');counts.push(line('Surau Kejiranan',b.surau));areas.push('Surau Kejiranan: Min. 0.50 ekar');totals.push(`Surau Kejiranan: Min. ${(b.surau*.5).toFixed(2)} ekar`)}result.innerHTML=names.length?names.map(nameLine).join(''):'Tidak dapat dikira';result.style.cssText+='text-align:left;line-height:1.35;';rows[0].innerHTML=counts.length?counts.join(''):'0';rows[1].innerHTML=areas.length?areas.map(x=>`<span style="display:block;text-align:right;line-height:1.45;color:#172234;font-weight:700;">${x}</span>`).join(''):'—';rows[2].innerHTML=totals.length?totals.map(x=>`<span style="display:block;text-align:right;line-height:1.45;color:#172234;font-weight:700;">${x}</span>`).join(''):'—';if(note)note.textContent=`Religious Facility Engine v1.1: Anggaran penduduk Islam ${fmt(pop)} orang. Pecahan awal menggunakan hierarki kluster GPP: bagi setiap 10,000 penduduk Islam, 1 Masjid Bandar + 2 Masjid Kejiranan + 4 Surau Kejiranan; baki tadahan diproses mengikut ambang 2,500 dan 5,000. Keputusan akhir tertakluk PBT/Pihak Berkuasa Agama.`;if(src)src.textContent='GPP Rumah Ibadat Islam 2023 — GPK 4.3 & 4.4';if(type&&type.textContent.trim()==='Keagamaan')type.textContent='Kemudahan Keagamaan';busy=false}
function schedule(){requestAnimationFrame(()=>requestAnimationFrame(enhance))}
function init(){schedule();const target=$('communityCards');if(target)new MutationObserver(m=>{if(busy)return;const replaced=m.some(x=>[...x.addedNodes].some(n=>n.nodeType===1&&n.classList?.contains('community-card')));if(replaced)schedule()}).observe(target,{childList:true});['totalUnits','housingTable','muslimPopulation'].forEach(id=>{const e=$(id);if(e)new MutationObserver(schedule).observe(e,{childList:true,subtree:true,characterData:true})});document.addEventListener('input',e=>{if(e.target.matches('#household,#muslimPopulation'))schedule()});document.addEventListener('change',e=>{if(e.target.matches('#muslimMode'))schedule()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();